name: immutable
description: Immutable collections for Dart
version: 0.0.3
author: Kwang Yul Seo <kwangyul.seo@gmail.com>
homepage: https://github.com/kseo/immutable

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  range: '^1.1.1'
  test: '>=0.12.0 <0.13.0'
