name: immutable
description: Immutable collections for Dart
version: 0.0.4
author: Kwang Yul Seo <kwangyul.seo@gmail.com>
homepage: https://github.com/kseo/immutable

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  quiver_check: '>=1.0.0-dev.1<1.1.0'

dev_dependencies:
  quiver_iterables: '>=1.0.0-dev.1<1.1.0'
  test: '>=0.12.0 <0.13.0'
